#!/usr/bin/env python
"""Regenerate the tables, figures and quoted numbers of the paper from the CSV files.

Examples
--------
From the reference results (the default)::

    python scripts/make_paper_assets.py

From a rerun, into a separate folder::

    python scripts/make_paper_assets.py --results-dir outputs --out outputs/paper_assets

Written files (``--out``, default ``paper_assets/``):

* ``tables/table{1..4}_*.tex`` (LaTeX with booktabs) and ``.md`` (Markdown):
  the test systems, the primary comparison at S = 1,000, the scenario scaling and
  the component analysis;
* ``figures/fig{2,3,4}_*.pdf`` and ``.png`` (300 dpi): solution time, speedup with
  the minimum active-set size, and evaluation-set unserved energy;
* ``numbers.md``: every number quoted in the results of the paper with its source
  file and column, the value computed from it, and whether the two agree;
* ``README.md``: an index of these files.

Only pandas, NumPy, SciPy and matplotlib are used; no solver is needed. A file
that does not exist yet is shown as ``not yet generated`` in ``numbers.md``
and ``n/a`` in the tables. Wall-clock times and speedups that differ from the
paper, as they do in any rerun, are counted separately as ``time differs``. The
exit status is 1 when another computed number differs from the printed one and
``--strict`` is given.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

from pisasr import reporting as rp
from pisasr.paths import DATA_DIR, REFERENCE_DIR, REPO_ROOT, check_layout, display_path, run_script


def parse_args(argv=None) -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Regenerate the paper's tables, figures and numbers from the CSV files.")
    p.add_argument("--results-dir", default=str(REFERENCE_DIR),
                   help="results folder to read, results (default) or outputs")
    p.add_argument("--data-dir", default=str(DATA_DIR), help="processed input data (default: data/)")
    p.add_argument("--out", default=str(REPO_ROOT / "paper_assets"), help="destination folder (default: paper_assets/)")
    p.add_argument("--no-figures", action="store_true", help="skip the figures (faster)")
    p.add_argument("--strict", action="store_true", help="exit with status 1 if any number differs from the paper")
    return p.parse_args(argv)


TABLES = [
    ("table1_systems", "Table 1. The two synthetic Texas test fleets"),
    ("table2_primary", "Table 2. Primary comparison at S = 1,000 on both systems"),
    ("table3_scaling", "Table 3. Scenario scaling: PI-SASR versus the full stochastic UC"),
    ("table4_components", "Table 4. Component analysis at equal active-set size (TX-123BT, S = 1,000)"),
]
FIGURES = [
    ("fig2_solution_time", "Figure 2. Solution time versus the number of scenarios S (log-log)"),
    ("fig3_speedup_and_kmin", "Figure 3. (a) Speedup of PI-SASR over the full model; "
                              "(b) minimum active-set size K_min(tau) meeting a benchmark-gap tolerance tau"),
    ("fig4_unserved_energy", "Figure 4. Evaluation-set unserved-energy rate under generator outages (log scale)"),
]


def _index(out: Path, results_label: str, files: list[Path]) -> str:
    """README of the asset folder: tables, figures (shown inline) and the register of numbers."""
    have = {str(f.relative_to(out)) for f in files}
    lines = [
        "# Paper assets",
        "",
        f"Generated by `python scripts/make_paper_assets.py` from `{results_label}/` and `data/`; "
        "do not edit these files by hand. `docs/RESULTS_GUIDE.md` names the files and columns behind "
        "every table, figure and number.",
        "",
        "## Tables",
        "",
        "The LaTeX versions need the packages `booktabs`, `multirow`, `threeparttable` and `graphicx`.",
        "",
        "| Table | LaTeX | Markdown |",
        "|---|---|---|",
    ]
    for stem, title in TABLES:
        tex, md = f"tables/{stem}.tex", f"tables/{stem}.md"
        if tex in have:
            lines.append(f"| {title} | [`{tex}`]({tex}) | [`{md}`]({md}) |")
    figures = [(stem, title) for stem, title in FIGURES if f"figures/{stem}.png" in have]
    if figures:
        lines += ["", "## Figures", ""]
        for stem, title in figures:
            lines += [f"**{title}.** PDF: [`figures/{stem}.pdf`](figures/{stem}.pdf)", "",
                      f"![{title}](figures/{stem}.png)", ""]
    lines += ["## Numbers", "",
              "[`numbers.md`](numbers.md) lists every number quoted in the results of the paper with its "
              "source file and column, the value computed from it, and whether the two agree."]
    return "\n".join(lines) + "\n"


def main(argv=None) -> int:
    args = parse_args(argv)
    results_dir = rp.resolve_dir(args.results_dir)
    data_dir = rp.resolve_dir(args.data_dir)
    check_layout([d for d in (results_dir, data_dir) if d in (REFERENCE_DIR, DATA_DIR)])
    out = Path(args.out).expanduser().resolve()
    label = results_dir.name
    src = rp.Sources(results_dir, data_dir)

    written = rp.write_tables(src, out / "tables")
    if not args.no_figures:
        written += rp.write_figures(src, out / "figures")
    numbers_path, register = rp.write_numbers(src, out, results_label=label)
    written.append(numbers_path)
    index = out / "README.md"
    index.write_text(_index(out, label, written))

    claims = register.claims
    bad = [c for c in claims if c.status == "NO"]
    timed = [c for c in claims if c.status == "time differs"]
    missing = [c for c in claims if c.status == "not yet generated"]
    print(f"[assets] wrote {len(written) + 1} files to {display_path(out)}")
    print(f"[assets] {len(claims)} numbers checked: {sum(c.status == 'yes' for c in claims)} agree, "
          f"{len(bad)} differ, "
          + (f"{len(timed)} times or speedups differ (expected for a rerun), " if timed else "")
          + f"{len(missing)} not yet generated")
    for c in bad:
        print(f"    DIFFERS  {c.group.split(' (')[0]}: {c.quantity}: paper {c.printed}, CSV {c.computed} ({c.unrounded})")
    for c in missing:
        print(f"    MISSING  {c.group.split(' (')[0]}: {c.quantity}: {c.computed}")
    return 1 if (args.strict and bad) else 0


if __name__ == "__main__":
    sys.exit(run_script(main))
